load("@rules_cc//cc:defs.bzl", "cc_library", "cc_binary", "cc_test")
load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")

cc_library(
    name = "simple_subscriber_lib",
    srcs = ["simple_subscriber.cpp"],
    hdrs = ["simple_subscriber.hpp"],
    deps = [
        "@rix",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "simple_subscriber",
    srcs = ["main.cpp"],
    deps = [
        ":simple_subscriber_lib",
        "@rix",
    ],
)

cc_test(
    name = "simple_subscriber_test",
    srcs = ["test.cpp"],
    deps = [
        ":simple_subscriber_lib",
        "@rix",
        "@googletest//:gtest_main",
    ],
)

# Refresh compile commands for all targets in the repository
refresh_compile_commands(
    name = "refresh_cc",
    targets = [
      "//..."
    ],
)
