load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "simple_subscriber_lib",
    srcs = ["simple_subscriber.cpp"],
    hdrs = ["simple_subscriber.hpp"],
    deps = [
        "@rix",
    ],
    visibility = ["//visibility:public"],
)

cc_binary(
    name = "simple_subscriber",
    srcs = ["main.cpp"],
    deps = [
        ":simple_subscriber_lib",
        "@rix",
    ],
)
